[package]
name = "vsnd_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
bsi_tools_lib = { path = "../bsi_tools_lib" }
toml = "0.8.19"
hound = "3.5.1"
serde = { version = "1.0.205", features = ["derive"] }
